# Generated by Django 6.0.2 on 2026-02-15 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Покупатель'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='customer', help_text='Определяет уровень доступа в системе', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('tg_username', models.CharField(blank=True, help_text='Ник в Telegram, например @username', max_length=100, verbose_name='Telegram')),
                ('address', models.TextField(blank=True, help_text='Основной адрес доставки', verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
