# Generated by Django 6.0.2 on 2026-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdek_pvz_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cdek_courier_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cdek_international_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_threshold_pvz', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_threshold_courier', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_threshold_international', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Настройки доставки',
                'verbose_name_plural': 'Настройки доставки',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_channel_url', models.URLField(blank=True)),
                ('support_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255)),
                ('group_id', models.CharField(blank=True, max_length=255)),
                ('channel_url', models.URLField(blank=True)),
                ('support_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Telegram настройки',
                'verbose_name_plural': 'Telegram настройки',
            },
        ),
    ]
