# Generated by Django 6.0.2 on 2026-03-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Способ доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('free_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бесплатно от суммы')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Доставка — способы',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Регион доставки')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Регион доставки',
                'verbose_name_plural': 'Доставка — регионы',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='DeliveryConfig',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='about_channel_url',
        ),
        migrations.RemoveField(
            model_name='telegramconfig',
            name='channel_url',
        ),
        migrations.RemoveField(
            model_name='telegramconfig',
            name='support_url',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='channel_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Telegram канал'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='support_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на поддержку'),
        ),
        migrations.AlterField(
            model_name='telegramconfig',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Токен Telegram бота'),
        ),
        migrations.AlterField(
            model_name='telegramconfig',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID группы для уведомлений'),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shop_config.deliveryregion', verbose_name='Регион'),
        ),
    ]
