# Generated by Django 6.0.2 on 2026-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_config', '0002_deliverymethod_deliveryregion_delete_deliveryconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryregion',
            options={'verbose_name': 'Настройки доставки', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.RemoveField(
            model_name='deliveryregion',
            name='name',
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_courier_free_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьером CDEK по адресу — бесплатно от'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_courier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьером CDEK по адресу — цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_pvz_free_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В пункт выдачи CDEK — бесплатно от'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_pvz_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В пункт выдачи CDEK — цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='code',
            field=models.CharField(choices=[('RU', 'Российская Федерация'), ('BY', 'Республика Беларусь'), ('KZ', 'Республика Казахстан')], max_length=2, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='channel_url',
            field=models.URLField(blank=True, verbose_name='Telegram канал'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='support_url',
            field=models.URLField(blank=True, verbose_name='Telegram поддержка'),
        ),
        migrations.DeleteModel(
            name='DeliveryMethod',
        ),
    ]
