# Generated by Django 6.0.2 on 2026-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_config', '0003_alter_deliveryregion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_courier_free_from_byn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьер — бесплатно от (Br)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_courier_free_from_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьер — бесплатно от (₸)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_courier_price_byn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьер — цена (Br)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_courier_price_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьер — цена (₸)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_pvz_free_from_byn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ПВЗ — бесплатно от (Br)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_pvz_free_from_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ПВЗ — бесплатно от (₸)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_pvz_price_byn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ПВЗ — цена (Br)'),
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='cdek_pvz_price_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ПВЗ — цена (₸)'),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='cdek_courier_free_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьер — бесплатно от (₽)'),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='cdek_courier_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курьер — цена (₽)'),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='cdek_pvz_free_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ПВЗ — бесплатно от (₽)'),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='cdek_pvz_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ПВЗ — цена (₽)'),
        ),
    ]
