# Generated by Django 6.0.2 on 2026-03-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_config', '0004_deliveryregion_cdek_courier_free_from_byn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryregion',
            name='cdek_courier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курьер — цена (₽)'),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='cdek_pvz_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ПВЗ — цена (₽)'),
        ),
    ]
