# Generated by Django 6.0.2 on 2026-02-15 12:32

import catalog.models
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Мужское'), ('F', 'Женское')], max_length=1)),
                ('is_material', models.BooleanField(default=False, help_text='Отметь, если это категория материалов (Хлопок, Шерсть и т.п.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок вывода в меню')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('main_image', models.ImageField(blank=True, help_text='Главное изображение товара', null=True, upload_to='products/', validators=[catalog.models.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, help_text='Материал из категорий-материалов', limit_choices_to={'is_material': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', validators=[catalog.models.validate_image_size])),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size_model', models.CharField(choices=[('standard', 'XXS–XXL'), ('uni', 'UNI')], help_text='Модель размеров для товаров в этой подкатегории', max_length=20)),
                ('cover_image', models.ImageField(upload_to='subcategories/', validators=[catalog.models.validate_image_size])),
                ('show_on_main', models.BooleanField(default=False, help_text='Показывать на главной (для выбора 4-х подкатегорий)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок вывода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.subcategory'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='Название цвета: Коричневый, Серый, Лавандовый и т.п.', max_length=50)),
                ('color_hex', colorfield.fields.ColorField(default='#000000', help_text='HEX-значение для кружочка, например #5C3A21', image_field=None, max_length=25, samples=None)),
                ('size', models.CharField(max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'color_name', 'size')},
            },
        ),
    ]
