# Generated by Django 6.0.2 on 2026-02-15 21:07

import catalog.models
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['gender', 'is_material', 'order', 'name'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии товара'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товара'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'подкатегорию', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Отметь, если это категория материалов (Хлопок, Шерсть и т.п.)', verbose_name='Является материалом'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Порядок вывода в меню', verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(help_text='Главное изображение товара', null=True, upload_to=catalog.models.product_main_image_path, validators=[catalog.models.validate_image_size], verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Материал из категорий-материалов', limit_choices_to={'is_material': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_products', to='catalog.category', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=catalog.models.product_main_image_path, validators=[catalog.models.validate_image_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=colorfield.fields.ColorField(default='#000000', help_text='HEX-значение для кружочка, например #5C3A21', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(help_text='Например: Коричневый, Серый, Лавандовый', max_length=50, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNI', 'UNI')], max_length=10, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=catalog.models.subcategory_cover_path, validators=[catalog.models.validate_image_size], verbose_name='Обложка подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Порядок вывода', verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='show_on_main',
            field=models.BooleanField(default=False, help_text='Показывать на главной (для выбора 4-х подкатегорий)', verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='size_model',
            field=models.CharField(choices=[('standard', 'XXS–XXL'), ('uni', 'UNI')], help_text='Модель размеров для товаров в этой подкатегории', max_length=20, verbose_name='Модель размеров'),
        ),
    ]
