# Generated by Django 6.0.2 on 2026-02-15 21:28

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(help_text='Материал из категорий-материалов', limit_choices_to={'is_material': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_products', to='catalog.category', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=catalog.models.product_gallery_image_path, validators=[catalog.models.validate_image_size], verbose_name='Изображение'),
        ),
    ]
