# Generated by Django 6.0.2 on 2026-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_price_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['gender', 'order', 'name'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Краткое описание (Футболки, блузки, комплекты и т.п.)', verbose_name='Описание подкатегории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Отметь, если эта подкатегория — раздел материалов', verbose_name='Является материалом'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Не использовать. Материалы теперь задаются в подкатегориях.', verbose_name='Является материалом (устарело)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', help_text='Например: Хлопок, Лен, Шерсть мериноса', max_length=200, verbose_name='Материал'),
        ),
    ]
