# Generated by Django 6.0.2 on 2026-02-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options_subcategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_material',
        ),
    ]
