# Generated by Django 6.0.2 on 2026-02-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_category_is_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'gender', 'name'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
