# Generated by Django 6.0.2 on 2026-02-23 17:27

import tinymce.models
from django.db import migrations, models
from decimal import Decimal

def fill_prices(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")

    products = []

    for product in Product.objects.all():
        product.price_rub = product.price
        product.price_kzt = product.price * Decimal("5")
        product.price_byn = product.price * Decimal("0.035")

        products.append(product)

    Product.objects.bulk_update(
        products,
        ['price_rub', 'price_kzt', 'price_byn']
    )

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['color_hex', 'id'], 'verbose_name': 'Вариант товара',
                     'verbose_name_plural': 'Варианты товара'},
        ),

        migrations.AddField(
            model_name='product',
            name='price_byn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (BYN)'),
        ),

        migrations.AddField(
            model_name='product',
            name='price_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (KZT)'),
        ),

        migrations.AddField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (RUB)'),
        ),

        migrations.RunPython(fill_prices),

        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
