# Generated by Django 6.0.2 on 2026-03-05 17:11

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_remove_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=orders.models.generate_order_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('shipped', 'Передан в доставку'), ('completed', 'Доставлен'), ('cancelled', 'Отменён')], default='created', max_length=20)),
                ('country', models.CharField(choices=[('RU', 'Российская Федерация'), ('KZ', 'Казахстан'), ('BY', 'Беларусь')], max_length=2)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant')),
            ],
        ),
    ]
