# Generated by Django 6.0.2 on 2026-03-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Доп. данные доставки'),
        ),
    ]
