# Generated by Django 6.0.2 on 2026-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('cdek_pvz', 'СДЭК — пункт выдачи'), ('cdek_courier', 'СДЭК — курьер')], max_length=20, verbose_name='Способ доставки'),
        ),
    ]
