# Generated by Django 6.0.2 on 2026-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_first_name_order_last_name_order_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('assembly', 'В сборке'), ('in_way', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='assembly', max_length=20, verbose_name='Статус'),
        ),
    ]
