# Generated by Django 6.0.2 on 2026-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа YooKassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('assembly', 'В сборке'), ('in_way', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='assembly', max_length=20, verbose_name='Статус'),
        ),
    ]
