# Generated by Django 6.0.2 on 2026-03-29 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_payment_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales_by_month', 'Продажи по месяцам'), ('average_check', 'Средний чек'), ('top_products', 'Популярные товары')], max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('format', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='processing', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
