# Generated by Django 6.0.2 on 2026-03-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('assembly', 'В сборке'), ('in_way', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='assembly', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(verbose_name='Дата от'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(verbose_name='Дата до'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('xlsx', 'Excel')], default='xlsx', max_length=10, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_by_month', 'Продажи по месяцам'), ('average_check', 'Средний чек'), ('top_products', 'Популярные товары')], max_length=50, verbose_name='Тип отчёта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус'),
        ),
    ]
